module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    '**/*.(t|j)s',
    '!**/*.spec.(t|j)s',
    '!**/*.module.ts',
    '!**/main.ts',
    '!**/main.worker.ts',
    '!**/instrument.ts',
    '!**/database/migrations/**',
    '!**/database/seed.ts',
    '!**/generated/**',
    '!**/collection/**',
  ],
  coverageDirectory: '../coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  testEnvironment: 'node',
  moduleNameMapper: {
    '^@/common(.*)$': '<rootDir>/common$1',
    '^@/config(.*)$': '<rootDir>/config$1',
    '^@/constants(.*)$': '<rootDir>/constants$1',
    '^@/database(.*)$': '<rootDir>/database$1',
    '^@/decorators(.*)$': '<rootDir>/decorators$1',
    '^@/exceptions(.*)$': '<rootDir>/exceptions$1',
    '^@/filters(.*)$': '<rootDir>/filters$1',
    '^@/generated(.*)$': '<rootDir>/generated$1',
    '^@/guards(.*)$': '<rootDir>/guards$1',
    '^@/interceptors(.*)$': '<rootDir>/interceptors$1',
    '^@/libs(.*)$': '<rootDir>/libs$1',
    '^@/shared(.*)$': '<rootDir>/shared$1',
    '^@/utils(.*)$': '<rootDir>/utils$1',
    '^@/tools(.*)$': '<rootDir>/tools$1',
  },
  setupFiles: ['../setup-jest.mjs'],
  cacheDirectory: '../.jest-cache',
  testTimeout: 120000,
};

